### PR TITLE
Add css parts

### PR DESCRIPTION
**Pull request by jordanjones243**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #116 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

* Add css parts to elements within the render functions of each of the three sub components

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by jason-capsule42 — CHANGES_REQUESTED** [review]
Let's be consistent in our naming here and use camelCase everywhere.

**Comment by jordanjones243** [comment]
> Let's be consistent in our naming here and use camelCase everywhere.

We use camel casing for classes, yes. But, when looking at other repos and how css parts are named there, we use hyphenated names. So, it's just a case of what format we want to be consistent with.

**Comment by blackfalcon** [comment]
We do have this for selectors, maybe we need to update this for things like attributes and CSS parts? 

https://auro.alaskaair.com/css/conventions

**Comment by blackfalcon** [comment]
Other than the debate on naming, this looks great. Thanks for the dependency bump too! 

:shipit:

**Comment by jordanjones243** [comment]
> We do have this for selectors, maybe we need to update this for things like attributes and CSS parts?
> 
> https://auro.alaskaair.com/css/conventions

Thanks for pointing me to this! We should be consistent and probably add something in there for CSS parts. Although we have a lot of hyphenated names out there for the CSS parts, I will go ahead and make those changes now.

**Review by blackfalcon — DISMISSED** [review]
The processed docs are out of date. Also, please add `"./demo/api.md",` to the following block in the package.json. This will ensure that when the build runs in the remote and if we missed running it locally, it will get committed back to the repo. 

```json
"assets": [
            "./package.json",
            "./CHANGELOG.md",
            "./README.md",
            "./docs/api.md",
            "./demo/index.md",
            "./demo/api.md"
          ]
```

**Review by jason-capsule42 — APPROVED** [review]

**Pull request merged**
